### PR TITLE
Overhaul of variants

### PR DESCRIPTION
**Pull request by epistularum**
Complete overall of variants based on the 印刷標準字体 (表外漢字表) https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kakuki/22/tosin03/index.html

All characters that are either a 簡易慣用字体 or have the 旧字 as a 印刷標準字体 and have the 新字 within JIS1 have been selected. In addition, characters that are both alternate of one another and are both 人名用漢字 (亙,亘-凜,凛) are included alongside design variations within JIS1 as stated by the 表外漢字字体表 (𠮟,叱-吞,呑-靱,靭-﨟,臈)

Characters excluded based on the criteria above:
```
# 人名用漢字 新字体
kyuji is not hyoujun
兔,兎
廚,厨
廏,厩
堯,尭
巖,巌
彥,彦
晉,晋
槇,槙
煕,熙
瑤,瑶
祿,禄
穰,穣
聰,聡
讚,讃
遙,遥

# 表外漢字だけに適用されるデザイン差
design variation is outside jis
柵,栅
荊,荆
頽,頹
稽,𥡴

# JIS1 拡張新字体
kyuji is not hyoujun
㵎,澗
礪,砺
礦,砿
龝,穐

```

Characters removed from original variant file:
```
姸	妍
拋	抛
筓	笄
腁	胼
鷽	鴬
```

### CODE REVIEW

**Comment by stephenmk** [comment]
Thanks for putting this together. I see a lot of new variants in here that I'm surprised I didn't have already.

The additions all look reasonable to me, but I'm not so sure about the removals. These are all kanji that the dictionary publishers have been inconsistent about, and I think it's useful to have these alternatives in the list.


<details>
    <summary>姸, 妍: It seems new publications all use 姸, but older versions of dictionaries (pictured: nikkoku and daijisen on kotobank.jp) used 妍</summary>


</details>

<details>
    <summary>拋, 抛: Sankoku8 uses 拋, Daijirin2 uses 抛, and Smk8 has an SVG image that appears somewhere in between the two</summary>


</details>

<details>
    <summary>筓, 笄: Sankoku8 and Smk8 use 筓, but Daijirin2 uses 笄 for the same word</summary>


</details>

<details>
    <summary>腁, 胼: Sankoku8 and Smk8 use 腁, but Daijirin2 uses 胼 for the same word</summary>


</details>

For 鷽 and 鴬, [鴬 is listed as an extended shinjitai on wikipedia](https://en.wikipedia.org/wiki/Extended_shinjitai#Creation_of_extended_shinjitai), for example. I don't think it hurts to have this alternative form in search keys in order to aid lookups, but this one doesn't seem too important.

I see that the 竜,龍 pair was also removed. Was this intentional? I think this pair is especially useful since it's so common.

**Comment by epistularum** [comment]
For these characters, either the kyuji is not within jis at all or the 拡張新字体 has a jis value lower than the kyuji. I'll analyze all such occurrences and add them.
姸	妍
筓	笄
腁	胼

竜 is a jouyou kanji so it's very hard to justify the use of its kyujitai. If we are to add kyujitai of jouyou kanji we will need to find a logic for it, perhaps same as above?
竜,龍

While 鷽 can technically be simplified to 鴬 it is not common in the japanese language and rather a chinese usage. In Japanese 鴬 is used as the simplified form of 鶯.
鷽	鴬

This pair seems like another instance of the correct character to being inside jis. This is a design variation that is outside the scope of 新字体 and 表外漢字字体表. I will need to compile new data for it.
拋, 抛

**Comment by stephenmk** [comment]
The 篡／簒 pair is another good one. The new editions of shinmeikai and sankoku actually display the 16 stroke version in SVG images rather than using the more common 17 stroke unicode character.

**Comment by epistularum** [comment]
Sorry for the long wait @stephenmk  I have finished analyzing and compiling the data, what do you think?

New candidates are as follows:

a design variation as per the 表外漢字字体表 that is within JIS
叱	𠮟
呑	吞
靱	靭
﨟	臈

簡易慣用字体 as per the 表外漢字字体表
唖	啞
噛	嚙
屏	屛
并	幷
弯	彎
掻	搔
撹	攪
桝	枡
沪	濾
繍	繡
蒋	蔣
蝋	蠟
醤	醬
頴	穎
鴎	鷗
鹸	鹼
麹	麴

拡張新字体 within JIS1/2 with its 旧字 being JIS3/4
侠1	俠3
倶1	俱3
剥1	剝3
嘘1	噓3
嚢1	囊3
填1	塡3
屡1	屢3
掴1	摑3
涜1	瀆3
溌1	潑3
焔1	焰3
箪1	簞3
繋1	繫3
莱1	萊3
蝉1	蟬3
躯1	軀3
醗1	醱3
頬1	頰3
顛1	顚3
騨1	驒3
妍2	姸3
攅2	攢3
杤2	𣜜4
档2	檔3
椢2	槶3
槞2	櫳4
絋2	纊3
纉2	纘4
陦2	隯4

拡張新字体 within JIS1/2 containing the component 开 with its 旧字 being outside JIS
笄2	筓
迸2	逬
胼2	腁
駢2	騈

a minor design variation within JIS that has its correct character outside JIS based on 漢検's kanji dictionary
抛2	拋
簒2	篡

**Comment by stephenmk** [comment]
So in comparison with [the latest version of the variant_kanji.csv file](https://github.com/stephenmk/jitenbot/blob/d37c3aca5bbc308289a5f89e83534a42ce3471a4/data/entries/variant_kanji.csv), from the candidates listed in the above comment it looks like we'd be adding 17 new pairs.

old style | new style
-|-
﨟|臈
幷|并
彎|弯
攢|攅
𣜜|杤
桝|枡
槶|椢
檔|档
櫳|槞
濾|沪
纊|絋
纘|纉
蔣|蒋
逬|迸
隯|陦
頴|穎
騈|駢

And removing 8 pairs


old style | new style | reason for removal
-|-|-
儘|侭|儘 is JIS2; new style isn't used in dictionaries
凜|凛| ?
禱|祷| ?
籠|篭|籠 is JIS2; new style isn't used in dictionaries
藪|薮|藪 is JIS2; new style isn't used in dictionaries
鶯|鴬|鶯 is JIS2; new style isn't used in dictionaries
鷽|鴬|Not common in Japanese
龍|竜|龍 is JIS1; old style isn't used in dictionaries

I don't see the 禱,祷 pair in the analysis (seems they are both 人名用) but it's probably a good pair to keep. I see dictionaries using both forms.

For 凛,凜 I see dictionaries using both forms e.g. in りりしい.  Looks like this was noted in the analysis as well.

By the way, [I just updated the way](https://github.com/stephenmk/jitenbot/commit/8f30f9419d0403952bfc4ae7c81fc999693dcd43) these variant kanji are used to generate search keys. I'll quote what I wrote in the commit:

> Prior to this commit, the program would only add variant kanji forms in one direction. For example, an additional search key for 掴む would be added if a 摑む headword was found in a dictionary, but a search key for 摑む would not be added to 掴む.
>
> Search keys are now added in both directions (old-to-new and new-to-old).

I originally set it up to add in one direction because I didn't think the old-style search keys would be very useful, but recently I came across 柔靱 and was annoyed to find that my dictionaries only had 柔靭. So I think this change is an improvement.

**Comment by epistularum** [comment]
> I don't see the 禱,祷 pair in the analysis (seems they are both 人名用) but it's probably a good pair to keep. I see dictionaries using both forms.

This is an oversight on my part as it is the only 人名用漢字 with its 旧字 being JIS3/4. It should be included.

>For 凛,凜 I see dictionaries using both forms e.g. in りりしい. Looks like this was noted in the analysis as well.

I have forgotten to analyze 人名用漢字 and it looks like another condition needs to be added. By default, only the 新字 is used UNLESS the 旧字体 is an 印刷標準字体 then both form can be used depending on the dictionary. An exception can be made for  亘/凛 as they are not really considered as being in a 旧字 relationship.

A match is considered when the 旧字 is used (h refers to the character being 印刷標準字体).
亘1	亙1 - different characters
兎h1	兔2
凛2	凜2 - 大辞林/新明国/明鏡/三国/大辞泉/広辞苑/日国
厨h1	廚2
厩h1	廏2
尭1	堯2 - 日国
巌1	巖2 - 日国
彦1	彥
晋1	晉2 - 日国
桧1	檜h2 - 大辞林/新明国/明鏡/三国/旺文社/岩波/大辞泉/日国
槙1	槇2 - 日国
熙2	煕2
瑶2	瑤2 - 日国
祢1	禰h1 - 広辞苑
祷1	禱h3 - 大辞林/新明国/明鏡/三国
禄1	祿2 - 日国
穣1	穰2 - 日国
聡1	聰2 - 日国
芦1	蘆h2 - 大辞林/新明国/明鏡/三国/旺文社/岩波/大辞泉/広辞苑/日国
讃h1	讚2 - 岩波/日国
遥1	遙2 - 日国

**Comment by stephenmk** [comment]
So in addition to the 17 pairs listed in my previous comment, we're now adding 3 more pairs: 禰,祢; 穎,頴; and 蘆,芦. We're removing 6 pairs, which are also listed in my previous comment with reasons. That sounds fine to me.

I thought again about the change to the search key generation logic that I mentioned before. It occurred to me that if we are assuming the user has some sort of hunspell dictionary to translate 龍 to 竜, we could also assume that it can translate these variant forms handled by jitenbot (e.g. 掴む to 摑む). So instead of generating multiple keys for both 掴 and 摑 forms, jitenbot could just change all occurrences of "掴" in keys into "摑". With this sort of setup, all entries for both 摑む and 掴む would be displayed to the user in one page, and there would be fewer keys to sift through in the search pane.

Right now I'm thinking it would be best to stay with the current setup. This is mainly for the sake of yomichan, where the hunspell preprocessing isn't available. There is a "Custom Text Replacement Patterns" feature in yomichan that can replicate this functionality, but users would need to configure it to account for the ~60 different variant kanji that we've settled on. When one of the yomichan successors becomes stable, maybe the developers could be convinced to make this setup more user friendly.

**Pull request merged**
